### ISSUE TITLE
Dismiss an alert after 5 sec

### ISSUE THREAD

**Issue by htarwara6245** [stakes/JSSAlertView#12]
If i dont want to add default ok button or any other button and i want to dismiss an alert after 5 sec,is there any way how to do that?

**Comment by stakes** [comment]
OK, pull the latest version with this commit https://github.com/stakes/JSSAlertView/commit/377eb2f9dfa36e2d10bbca4902191b0300d146ed

And use NSTimer to close the alert, something like this:

```swift
var alertview = JSSAlertView().show(self, title: "I'll close myself in five seconds")
var timer = NSTimer.scheduledTimerWithTimeInterval(5, target: alertview, selector: Selector("close"), userInfo: nil, repeats: false)
```
