### ISSUE TITLE
addCancelAction - Still calls action

### ISSUE THREAD

**Issue by v1n2e7t** [stakes/JSSAlertView#13]
var alertview = JSSAlertView().show(self, title: "title", buttonText: "Yes", cancelButtonText: "No")
        alertview.addAction(self.calltimeboosts)
        alertview.addCancelAction(self.uploadImgs)

Here is a simple alert view with a cancel button. When i click the action button it also calls the cancel button. at least in my opinion, it should be two separated actions. not linked.
Can we make a separated action for cancel

**Comment by sman591** [comment]
Oh wow, you're right. That's my fault. Will submit PR shortly

**Comment by stakes** [comment]
It's actually my fault for succumbing to self-imposed pressure and not testing things before merging. :disappointed: Thanks @sman591 and @v1n2e7t
