### ISSUE TITLE
Strong reference cycle

### ISSUE THREAD

**Issue by nafetswirth** [stakes/JSSAlertView#16]
Hey, 
I was experiencing an issue where the alertview wouldn't be deallocated properly when deallocationg the rootview without dismissng the alert. I think the reason is the strong reference to the rootviewcontroller. 
I'm just asking if the strong reference is intended to prevent premature deallocation, before issuing a pull request. 

Thanks.

**Comment by stakes** [comment]
Nonono all good - please send a PR and I'll merge it in! THANKS :+1:
