### ISSUE TITLE
Destroying Navigation Controller

### ISSUE THREAD

**Issue by hatemalimam** [stakes/JSSAlertView#18]
The AlertView is somehow breaking the Navigation sequence, here's a simple case: 

NavigationController > ViewController > UITableViewController > Click Cell > Show JSSAlertView > Close JSSAlertView > Hit Back > nothing is done, navigation breaks.

Any idea why this is happening ?

**Comment by ArjunSa786** [comment]
i am also having same problem,

**Comment by stakes** [comment]
Does this PR solve it? https://github.com/stakes/JSSAlertView/pull/19

**Comment by syky27** [comment]
Tested, and it seems it is working.
