### ISSUE TITLE
AlertView is scrollable  

### ISSUE THREAD

**Issue by perwyl** [stakes/JSSAlertView#22]
I displayed the alert view above a tableview, as tableview is scrollable, i can scroll `JSSAlertView` to reveal the tableview cells. Would like to freeze the `root view controller`. 

I'm using Xcode 6.4, swift 1.2 and IOS8.

**Comment by jkritikos** [comment]
Having the same issue with a tableview - I tried using the tableview's navigation controller as the target view for the alert and that fixed it BUT, it messed up with the navigation stack.

**Comment by syky27** [comment]
see #26

**Comment by perwyl** [comment]
Another way i found out to add it as a subview to keyWindow without disable scrolling.

```   
self.rootViewController = viewController
self.rootViewController.addChildViewController(self)
self.rootViewController.view.addSubview(view)

let rv = UIApplication.sharedApplication().keyWindow! as UIWindow	 
rv.addSubview(view)	 
view.frame = rv.bounds
```
