### ISSUE TITLE
Navigation View

### ISSUE THREAD

**Issue by luciano-work** [stakes/JSSAlertView#23]
If you have a "show" Segue navigation and add this Code:

@IBAction func kitchenSinkAlertViewButtonPress() {
        var customIcon = UIImage(named: "lightbulb")
        var alertview = JSSAlertView().show(self, title: "Kitchen sink", text: "Here's a modal alert with descriptive text, an icon, custom fonts and a custom color", buttonText: "Sweet", color: UIColorFromHex(0xE0107A, alpha: 1), iconImage: customIcon)
        alertview.addAction(closeCallback)
        alertview.setTitleFont("ClearSans-Bold")
        alertview.setTextFont("ClearSans")
        alertview.setButtonFont("ClearSans-Light")
        alertview.setTextTheme(.Light)
    }

this alert will not appear :(
but appear in RootVC

My Solution is change this:
self.rootViewController = viewController.view.window!.rootViewController
self.rootViewController.addChildViewController(self)
self.rootViewController.view.addSubview(view)

For this:

self.rootViewController = viewController
self.rootViewController.addChildViewController(self)
self.rootViewController.view.addSubview(view)

but, how to show the subview above the Navigation Controller ?

All the best :)

**Comment by luciano-work** [comment]
my solution for this problem is:
self.rootViewController = viewController.navigationController 

:smile: :smile:

**Comment by Maverick25** [comment]
@luciano-work Such a simple solution!! Thank you :)

**Comment by luciano-work** [comment]
@Maverick25 :smile:
