### ISSUE TITLE
closeView when tapping JSSAlertView

### ISSUE THREAD

**Issue by polis80cy** [stakes/JSSAlertView#25]
Hi, nice control!

Is there any way to hide the alert view when tapping on it or anywhere else besides the button? I don't want a cancel button but need to replicate such cancel functionality by tapping anywhere else.

**Comment by syky27** [comment]
Hi!

This is not supported (yet). I am labelling this as Feature Request and we will think about it.

Thanks for using JSSAlertView.

**Comment by syky27** [comment]
Hi! 

I have implemented what you requested. You can use it with following:

```swift
JSSAlertView().show(self, title: "Boring and basic, but with a multi-line title and no buttons", noButtons: true)
```

When `noButtons: true` there will be no button even if you set texts for them.

Stay tuned to JSSAlertView
