### ISSUE TITLE
ModalViewController Issue

### ISSUE THREAD

**Issue by mikemane** [stakes/JSSAlertView#27]
Hello, 
When i present the alert view in a modal view controller that was presented from another view controller.
Nothing happens when i dismiss said view controller. 
The alert pops up from the parent view controller.

**Comment by web-melt** [comment]
check if #26 fixes you issue, should if I read the code correctly.

@stakes  any chance #26 gets merged?

**Comment by mikemane** [comment]
Thanks that solved my problem

**Comment by SwithFr** [comment]
I have the same issue, so it's seem not fixed.
