### ISSUE TITLE
Improper Size / Position when presented from .FormSheet or Split Screen

### ISSUE THREAD

**Issue by mvoccola** [stakes/JSSAlertView#30]
Alert view sizes itself incorrectly when being presented from a non-fullscreen ViewController. The AlertView appears to inherit the size of the entire screen rather than the frame of the application or the bounds of a modally presented FormSheet view controller, from which the alert is presented.

The same behavior is present when using Split-Screen on iPad.

![simulator screen shot feb 29 2016 12 02 52 pm](https://cloud.githubusercontent.com/assets/11658414/13402002/6365dc6c-dedc-11e5-8c01-8a875038f091.png)

**Comment by mvoccola** [comment]
in `JSSAlertView.swift`, in the `viewDidLayoutSubviews()` method, change the `size` value from `UIScreen.mainScreen().bounds.size` to `UIApplication.sharedApplication().windows[0].bounds`

**Comment by mvoccola** [comment]
in JSSAlertView.swift, in the viewDidLayoutSubviews() method, change the size value from `UIScreen.mainScreen().bounds.size` to:

```
var size  = UIApplication.sharedApplication().windows[0].bounds
if let i = UIApplication.topViewController()?.view.bounds.size {
    size = CGRect(origin: CGPoint(), size: i)
}
```

**Comment by syky27** [comment]
Thanks for reporting.

However I am unable to locate code you are referring to.

Thanks.

**Comment by mvoccola** [comment]
That line is located in JSSAlertView.swift under `viewDidLayoutSubviews()`

**Comment by syky27** [comment]
The current problem is that JSSAlertView gets rendered under the `.FormSheet`

**Comment by mvoccola** [comment]
There is a similar problem present when presenting the alert in split-screen mode on iPad as well. That behavior is resolved by modifying the line of code I mentioned earlier in the comments.

**Comment by syky27** [comment]
I am sorry but I don't quite get you.

Right now how it works is that JSSAlertView gets always placed right into middle of the screen.
The height and width gets calculated from this function

```swift
func screenSize() -> CGSize {
	let screenSize = UIScreen.mainScreen().bounds.size
	if (NSFoundationVersionNumber <= NSFoundationVersionNumber_iOS_7_1) && UIInterfaceOrientationIsLandscape(UIApplication.sharedApplication().statusBarOrientation) {
	    return CGSizeMake(screenSize.height, screenSize.width)
		}
	return screenSize
}
```

The height gets placed into:

```swift
let size = self.screenSize()
self.viewWidth = size.width
self.viewHeight = size.height
```

And those values are used this way:

```swift
self.containerView.frame = CGRect(x: (self.viewWidth!-self.alertWidth)/2, y: (self.viewHeight! - yPos)/2, width: self.alertWidth, height: yPos)
```

When running this code JSSAlertView, gets correctly placed into middle of screen, but it is hidden behind the view that is presented as `.FormSheet`

Now about your code it doesn't really make any sense to me this is why
1.  `UIApplication` has no method called `topViewController` on the other hand `UINavigationController` has this method and it points to the top `UIViewController` in its navigation stack.
2. You are assigning  `CGRect` into variable size and there is no reason to do that

If you could elaborate on this it would be much appreciated, because right now I don't have the slightest idea how your code could ever work.

Thanks for contribution!

**Comment by syky27** [comment]
For now, I was finally able to completely reproduce your, issue when changing this

```swift
self.rootViewController = viewController.view.window!.rootViewController
```

to this

```swift
self.rootViewController = viewController
```

**Comment by mvoccola** [comment]
To temporarily relieve some of the misunderstanding, `topViewController` in my example is a `UIApplication` extension I implemented in the project and is defined below:

```
extension UIApplication {
    class func topViewController(base: UIViewController? = UIApplication.sharedApplication().keyWindow?.rootViewController) -> UIViewController? {
        if let nav = base as? UINavigationController {
            return topViewController(nav.visibleViewController)
        }
        if let tab = base as? UITabBarController {
            if let selected = tab.selectedViewController {
                return topViewController(selected)
            }
        }
        if let presented = base?.presentedViewController {
            return topViewController(presented)
        }
        return base
    }
}
```

Looks to accomplish the same thing as your last comment.

To be clear, it seems that the issue with presenting the alert on iPad when in split-screen (multi-tasking) mode is that the size of the alert is calculated from the size of the screen, not the size of the current application window. When I refer to this problem, I am referring to any presentation of the alert, not just when presented from a .FormSheet. But again, in your last comment you are getting the size of the window, not the size of the entire screen, so that should alleviate any issues during the presentation.

**Comment by syky27** [comment]
Yeah I know that the size is calculated badly, I have already find a solution to this issue, I am implementing as we speak.

**Comment by syky27** [comment]
@mvoccola Thank you for reporting this issue and stay tuned to JSSAlertView
