### ISSUE TITLE
Swift 1.2

### ISSUE THREAD

**Issue by b992** [stakes/JSSAlertView#8]
Please update the code to be compatible with Swift 1.2!

Thank you! :)

**Comment by blakeperdue** [comment]
Yep, the example project on swift 1.2 on xcode 6.3.1 gives 4 errors and won't build.

**Comment by stakes** [comment]
Thanks for the heads-up!

**Comment by youclavier** [comment]
Hi I really like the UIAlertView you design, could you please fix the 4 bugs in Swift 1.2? Thank you so much~~~

**Comment by QUB3X** [comment]
I just commented  <pre>//    required override init() {
//        super.init()
//    }</pre>

and at Line 387 removed the `?`.
It seems working (I mean, at least it compiles!)

**Comment by youclavier** [comment]
@QUB3X  yes if you delete it. It can compiles, but it seems that the alertview dialog will be cover by the current viewcontroller's view instead of display at the front.

**Comment by stakes** [comment]
This PR should solve it and is merged into master:

https://github.com/stakes/JSSAlertView/pull/9
